import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './_components/Navbar'
import Footer from './_components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <div className='border-b-2 border-red-500 border-opacity-30'>
        <Navbar />
      </div>
      <div className='md:h-screen h-auto'>
        {children}
      </div>
      <Footer />
    </div>
  )
}
